spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#order-service configuration
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/orders/**

#analytics-service configuration
spring.cloud.gateway.routes[1].id=analytics-service
spring.cloud.gateway.routes[1].uri=lb://ANALYTICS-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/analytics/**

app.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437