spring.application.name=interaction-service
server.port=8082


spring.datasource.url=${INTERACT_DB_URL}
spring.datasource.username=${INTERACT_DB_USERNAME}
spring.datasource.password=${INTERACT_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect